baseurl = "/"
languageCode = "he-us"
languageLang = "he"
title = "חוויה להשכיר"
disableKinds = ["RSS"]

[permalinks]
  workshops = "/סדנאות/:title"

[params]
  home = "Home"

  [params.slider]
    enable = true
    title = "סדנאות מצוינות לילדים"
    subtitle = "חוויה להשכיר ממקמת באירוע שלך פעילויות חוויתיות במהירות וביעילות, תוך הקפדה על איכות התכנים, ההדרכה והחומרים."
    bgImage = "img/rentfun/main.jpg"
    btnText = "הזמיני עכשיו"
    url = "#"
